name: discovery plugin
description: does nothing
author: 
requirements:
configuration:
  properties:
    artifacts:
      type: string
    job-uuid-file-pattern:
      type: string
    failure-format:
      type: string
      enum:
        - classname
        - file
    fail-build-on-error:
      type: boolean
  required:
  additionalProperties: false